export const ADD_ENTITY_REQUEST = 'ADD_ENTITY_REQUEST';
export const ADD_ENTITY_SUCCESS = 'ADD_ENTITY_SUCCESS';
export const ADD_ENTITY_FAILURE = 'ADD_ENTITY_FAILURE';

export const FETCH_ENTITY_REQUEST = 'FETCH_ENTITY_REQUEST';
export const FETCH_ENTITY_SUCCESS = 'FETCH_ENTITY_SUCCESS';
export const FETCH_ENTITY_FAILURE = 'FETCH_ENTITY_FAILURE';

export const FETCH_ENTITIES_REQUEST = 'FETCH_ENTITIES_REQUEST';
export const FETCH_ENTITIES_SUCCESS = 'FETCH_ENTITIES_SUCCESS';
export const FETCH_ENTITIES_FAILURE = 'FETCH_ENTITIES_FAILURE';
